name: bmi_calculator
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.12.0"
  sleek_circular_slider : ^2.0.1

flutter_icons:
  android: true
  image_path: "image.jpg"

flutter:
  uses-material-design: true
  fonts:
    - family: Fasthand
      fonts:
        - asset: Fasthand-Regular.ttf
    - family: Outfit
      fonts:
        - asset:   Outfit-VariableFont_wght.ttf
    # - family: Open Sans
    #   fonts:
    #     - asset:   OpenSans-VariabeFont_wdth,wght.ttf
